"""added social links in userinfo model

Revision ID: d58ad35449e3
Revises: ee402765912d
Create Date: 2023-06-15 20:09:52.744291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58ad35449e3'
down_revision = 'ee402765912d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('vk_link', sa.String(length=500), nullable=True))
    op.add_column('user_info', sa.Column('telegram_link', sa.String(length=500), nullable=True))
    op.add_column('user_info', sa.Column('instagram_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'instagram_link')
    op.drop_column('user_info', 'telegram_link')
    op.drop_column('user_info', 'vk_link')
    # ### end Alembic commands ###
